execute pathogen#infect()

set shell=sh

" CONF {
" --------------------------------

"Set leader key
let mapleader = ","
set nocompatible " We don't want vi compatibility.

" Ignore extension files
set wildignore=*.dll,*.o,*.obj,*.bak,*.pyc,*.swp,*/.git/*,*/.svn/* " ignore these"
set term=ansi
set termencoding=utf-8
set encoding=utf-8
"}

" VISUALS {
" --------------------------------
set nowrap
set showmatch " show matching brackets
set showcmd

" show hidden chars
set list
set listchars=tab:->,trail:_

"Show menu with possible tab competions
set wildmenu

syntax enable
colorscheme molokai
set background=dark

" PLUGINS {
" --------------------------------

" Minibuffer Explorer Settings
let g:miniBufExplorerMoreThanOne = 1   " Open only when having more than one buffer
let g:miniBufExplUseSingleClick = 1    " Use single click
let g:miniBufExplCheckDupeBufs = 0     " Disable duplicated names feature
let g:miniBufExplShowBufNumbers = 1    " Omit buffer number
let g:miniBufExplModSelTarget = 1

" NERDTree
let NERDTreeWinPos = "left"      " left
let NERDTreeMouseMode = 3        " single click
let NERDTreeMinimalUI = 1        " without ? nor bookmarks
"}

" vim-airline
let g:airline_powerline_fonts = 1

set tabstop=2 " Tabs are 2 spaces
set softtabstop=2
set shiftwidth=2 " Tabs under smart indent
set autoindent
set smartindent
filetype plugin indent on
set smarttab
set expandtab

"Curor line
set cursorline
set number

"Allow switching buffers without writing to disk
set hidden

" SEARCH {
" --------------------------------
" Set incremental search
set incsearch
set hlsearch

" Set ignorecase
set ignorecase
set smartcase
"}

" Set terminal title to filename
set title

" Mappings {

vnoremap < <gv
vnoremap > >gv

map Y y$
map <leader>n <ESC>:NERDTreeToggle<RETURN>
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

noremap <C-J>     <C-W>j
noremap <C-K>     <C-W>k
noremap <C-H>     <C-W>h
noremap <C-L>     <C-W>l
" }

" Backups {
set nobackup      " Real man don't use backups
set nowritebackup
set noswapfile
" }

" GUI STUFF
if has("gui_running")
    set guioptions-=T " no toolbar set guioptions-=m " no menus
    set guioptions-=r " no scrollbar on the right
    set guioptions-=R " no scrollbar on the right
    set guioptions-=l " no scrollbar on the left
    set guioptions-=b " no scrollbar on the bottom

    set guifont=*
    set guifont=Inconsolata\ for\ Powerline:h16
endif
